<?php

/**
 *  @var MVC\model\User $user
 * @var string $title
 */

?>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title><?= $title ?></title>
<!--    <link rel="stylesheet" href="/styles.css">-->
</head>
<body>
    <div>
        <ul>
            <?php if (!$user): ?>
            <li>
                <a href="/user/register">Register</a>
            </li>
            <li>
                <a href="/user/login">Login</a>
            </li>
            <?php else: ?>
                <li>Welcome, <?= $user->getNickname() ?>! <a href="/user/logout">Logout</a></li>
            <?php endif; ?>
            <li>
                <a href="/news">News</a>
            </li>
        </ul>
    </div>